import { requireAuth } from "@/lib/session"
import { prisma } from "@/lib/db"
import { notFound } from "next/navigation"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import ReactMarkdown from "react-markdown"
import PrintButton from "./PrintButton"

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireAuth()
  const resolvedParams = await params

  const report = await prisma.report.findFirst({
    where: { id: resolvedParams.id, workspaceId: user.workspaceId },
    include: { generatedBy: true }
  })

  if (!report) return notFound()

  const parsedContent = JSON.parse(report.contentJson)
  const markdown = parsedContent.markdown || "No content generated."

  return (
    <div className="p-8 max-w-4xl mx-auto h-full">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href="/dashboard/reports" className="flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-gray-900">
          <ArrowLeft className="w-4 h-4" />
          Back to Reports
        </Link>
        <PrintButton />
      </div>

      <div className="bg-white p-10 rounded-2xl shadow-sm border border-gray-200 print:shadow-none print:border-none print:p-0">
        <div className="mb-10 pb-6 border-b border-gray-100">
          <h1 className="text-3xl font-extrabold tracking-tight text-gray-900 mb-4">{report.title}</h1>
          <div className="flex gap-6 text-sm text-gray-500">
            <div><strong>Period:</strong> {report.periodStart.toLocaleDateString()} - {report.periodEnd.toLocaleDateString()}</div>
            <div><strong>Generated By:</strong> {report.generatedBy.name}</div>
            <div><strong>Date:</strong> {report.createdAt.toLocaleDateString()}</div>
          </div>
        </div>

        <div className="prose prose-indigo max-w-none text-gray-700 leading-relaxed">
          <ReactMarkdown>{markdown}</ReactMarkdown>
        </div>
      </div>
    </div>
  )
}
