import { requireAuth } from "@/lib/session"
import { prisma } from "@/lib/db"
import Link from "next/link"
import { FileText, Plus } from "lucide-react"

export default async function ReportsPage() {
  const user = await requireAuth()

  const reports = await prisma.report.findMany({
    where: { workspaceId: user.workspaceId },
    orderBy: { createdAt: "desc" },
    include: { generatedBy: true }
  })

  return (
    <div className="p-8 max-w-5xl mx-auto h-full flex flex-col">
      <div className="sm:flex sm:items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold leading-6 text-gray-900">Voice of Customer Reports</h1>
          <p className="mt-2 text-sm text-gray-700">
            Generate and view weekly AI-synthesized digests of customer feedback.
          </p>
        </div>
        <div className="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
          <form action="/dashboard/reports/new">
            <button
              type="submit"
              className="flex items-center gap-2 rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500"
            >
              <Plus className="w-4 h-4" />
              Generate Report
            </button>
          </form>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <table className="min-w-full divide-y divide-gray-300">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Report Title</th>
              <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Period</th>
              <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Generated By</th>
              <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Date</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 bg-white">
            {reports.map((report: {
              id: string
              title: string
              periodStart: Date
              periodEnd: Date
              createdAt: Date
              generatedBy: { name: string | null }
            }) => (
              <tr key={report.id} className="hover:bg-gray-50 transition-colors">
                <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-indigo-600 sm:pl-6">
                  <Link href={`/dashboard/reports/${report.id}`} className="flex items-center gap-2 hover:underline">
                    <FileText className="w-4 h-4 text-indigo-400" />
                    {report.title}
                  </Link>
                </td>
                <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  {report.periodStart.toLocaleDateString()} - {report.periodEnd.toLocaleDateString()}
                </td>
                <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  {report.generatedBy.name}
                </td>
                <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  {report.createdAt.toLocaleDateString()}
                </td>
              </tr>
            ))}
            {reports.length === 0 && (
              <tr>
                <td colSpan={4} className="py-12 text-center text-sm text-gray-500 bg-gray-50/50">
                  <FileText className="w-8 h-8 text-gray-300 mx-auto mb-3" />
                  No reports generated yet. Click "Generate Report" to create your first weekly digest.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
